# Weather prediction
- platform: yr

- platform: template
  sensors:
    dome_water_sensor_battery_level:
      friendly_name: 'Dome Water Sensor Battery Level'
      value_template: '{{ states.zwave.dome_water_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: processor_use

- platform: yweather
  woeid: !secret yweather_woeid
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature
