# Weather prediction
- platform: yr

- platform: template
  sensors:
    dome_water_sensor_battery_level:
      friendly_name: 'Dome Water Sensor Battery Level'
      value_template: '{{ states.zwave.dome_water_sensor.attributes.battery_level }}'
      unit_of_measurement: '%'
    co_and_fire_alarm_battery_level:
      friendly_name: "CO And Fire Alarm Battery Level"
      value_template: '{{ states.zwave.co_and_fire_alarm.attributes.battery_level }}'
      unit_of_measurement: '%'
    status_co_and_fire_alarm:
      friendly_name: "CO And Fire Alarm Status"
      value_template: >-
          {%- if is_state("sensor.co_and_fire_alarm_alarm_type", "13") %}
              Idle
          {%- elif is_state("sensor.co_and_fire_alarm_alarm_type", "1") %}
              Fire Detected
          {%- elif is_state("sensor.co_and_fire_alarm_alarm_type", "2") %}
              Carbon Monoxide Detected
          {%- elif is_state("sensor.co_and_fire_alarm_alarm_type", "12") %}
              Alarm Testing
          {% else %}
              Unknown
          {%- endif %}

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: network_in
      arg: wlan0
    - type: network_out
      arg: wlan0
    - type: processor_use

- platform: yweather
  woeid: !secret yweather_woeid
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature

